### PR TITLE
Adding multipart-form support, updated demo.

### PR DESCRIPTION
**Pull request by NathanaelA**

### CODE REVIEW

**Comment by SuperAssassinNinja** [comment]
Can you merge this into Master pls?

**Comment by paoue74** [comment]
Hello,
 
I got problem with multipart upload by ns background http and happy that could be fixed ;)

**Comment by SuperAssassinNinja** [comment]
Still waiting =P

**Comment by narender56** [comment]
@NathanaelA  any update on pull request?

**Comment by NathanaelA** [comment]
@PanayotCankov - Any chance this can be merged soon?

**Comment by nalinimanduva** [comment]
Hi, Can we have this merged into master branch. We need this fix.

**Comment by SuperAssassinNinja** [comment]
Can you release this soon pls?

**Comment by NickIliev** [comment]
@SuperAssassinNinja , @NathanaelA  , @nalinimanduva , @narender56 

PR is now merged and published with versions 2.5.0 of [nativescript-background-http](https://www.npmjs.com/package/nativescript-background-http).

**Pull request merged**
