### PR TITLE
Implemented Canceling uploads

### PR DESCRIPTION
**Pull request by Icer2000**
Implemented canceling running uploads

I needed some trickery to get tsc to compile the code. (some <any> casts)
I also change the ios implementation to return common.task instead task for that.
Please review my changes.

### CODE REVIEW

**Comment by Icer2000** [comment]
I also added the option to auto delete the file after succesful upload

**Comment by Icer2000** [comment]
test and test2 were commits to install from my public fork, i can always undo them later on.

**Comment by lini** [comment]
Hi and thanks for your work!
I have a couple of suggestions that should be addressed before the PR can be merged.

- the android permissions should be updated to allow deleting files on the device. The `READ_EXTERNAL_STORAGE` permission in `nativescript-background-http/platforms/android/AndroidManifest.xml` should be replaced with `WRITE_EXTERNAL_STORAGE` (which includes read and write):
   ```XML
   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
   ```
- `package.json` files should not be modified for this request as it does not contain updated dependencies. You can undo those so only `.ts` and `.d.ts` files are modified.

**Comment by Icer2000** [comment]
Done undoig the package.json changes and added the WRITE permissions. Looking forward for the next release. :)

**Pull request merged**
